spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/totoro_blog?serverTimezone=GMT%2B8
    username: root
    password: 123456
token:
  #Token Custom Identifier
  header: Authorization
  #Token key
  secret: abcdefghijklmnopqrstuvwxyz1224
  #Token validity period (default 30 minutes)
  expireTime: 30
totoro:
  name: TotoroBlog
  version: 0.0.1
  copyrightYear: 2020
  profile: E:/working/personal/file
  addressEnabled: true